SYMBOLS = [
  "NVDA","MSFT","TSLA","AAPL","AMD","META","SPY","QQQ","GOOGL","AMZN",
  "NFLX","INTC","CSCO","BA","DIS","V","MA","JPM","BAC","WMT",
  "KO","PFE","MRK","XOM","CVX","T","VZ","UNH","HD","PG",
  "ABNB","ORCL","CRM","ADBE","AVGO","COST"
]
INVESTMENT_CAP = 250
LIVE_ORDERS = False
POLL_INTERVAL = 15
