SYMBOLS = [
  "NVDA","MSFT","TSLA","AAPL","AMD","META","SPY","QQQ","GOOGL","AMZN",
  "NFLX","INTC","CSCO","BA","DIS","V","MA","JPM","BAC","WMT",
  "KO","PFE","MRK","XOM","CVX","T","VZ","UNH","HD","PG",
  "ABNB","ORCL","CRM","ADBE","AVGO","COST"
]
INVESTMENT_CAP = 250
POLL_INTERVAL = 15
TICKER_INTERVAL = POLL_INTERVAL
LIVE_ORDERS = True
ENABLE_SHORTS = True
MIN_ORDER_USD = 1
MAX_OPEN_POSITIONS = 10
ORDER_TYPE = "market"
ORDER_TIF = "day"
