import pytz

# --- SCHWAB API CONFIG ---
# Paste your keys here from the Schwab Developer Portal
SCHWAB_APP_KEY = 'THvMSg6cKMv0DwUbLjSTKkbjA5QS4x52kcydCOdcaOehAWLX'
SCHWAB_APP_SECRET = 'HtkGArIuSxdp59OHCiWgvKoWBcAsYVMfw8GKtisS2BfF2b0W4aBGd10hCOnX6V7F'
SCHWAB_REDIRECT_URI = 'https://127.0.0.1'
SCHWAB_TOKEN_PATH = 'schwab_token.json'

# --- TRADING WINDOW (IST) ---
START_HOUR_IST = 9
START_MINUTE_IST = 30
END_HOUR_IST = 13
END_MINUTE_IST = 0
TIMEZONE = pytz.timezone('Asia/Kolkata')

# --- RISK PARAMETERS ---
MAX_DAILY_LOSS_PCT = 3.0
RISK_PER_TRADE_PCT = 0.5
MAX_SIMULTANEOUS_TRADES = 5
DEFAULT_SL_PCT = 1.5
DEFAULT_TP_PCT = 3.0

# --- WATCHLIST ---
WATCHLIST = ['NVDA', 'TSLA', 'AAPL', 'MSFT', 'AMD', 'META', 'SPY', 'QQQ']
